gui:
  nerdFontsVersion: "3"
keybinding:
  universal:
    nextBlock: <c-j>
    prevBlock: <c-k>
  commits:
    moveDownCommit: <disabled>
    moveUpCommit: <disabled>
git:
  pagers:
    - externalDiffCommand: "difft --color=always"
